services:
  rstudio:
    image: docker.io/tstuckey303/scs-analysis-r:1.5
    container_name: analysis_container_r
    ports:
      - "8787:8787"
    environment:
      - DISABLE_AUTH=true
    volumes:
      - "./.here:/home/rstudio/.here"
      - "./.config/rstudio:/home/rstudio/.config/rstudio"
      - "./_data:/home/rstudio/_data"
      - "./notebooks/R_Notebooks:/home/rstudio/notebooks/R_Notebooks"
    restart: unless-stopped

  sqlitebrowser:
    image: docker.io/linuxserver/sqlitebrowser:3.12.2
    container_name: analysis_container_sqlite
    ports:
    # 3000 for desktop GUI
    # 3001 for HTTPS GUI 
      - "3000:3000"
      - "3001:3001"
    volumes:
      - "./.config/sqlitebrowser:/config"
      - "./_data:/config/data"
    restart: unless-stopped 
